# Generated by Django 6.0 on 2026-01-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0005_facultymember_is_avc_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year_code',
            field=models.CharField(help_text='Format: "24-25" or "2024-2025" for academic year', max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
