# Generated by Django 6.0 on 2026-01-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0006_increase_year_code_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('code', models.CharField(choices=[('cardiac', 'Cardiac'), ('critical_care', 'Critical Care'), ('multispecialty', 'Multispecialty'), ('pain', 'Pain'), ('pediatric', 'Pediatric')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('chief', models.ForeignKey(blank=True, help_text='Division chief who can view division faculty data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions_led', to='reports_app.facultymember')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
    ]
