# Generated by Django 6.0 on 2026-01-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0007_add_division_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='access_token',
            field=models.CharField(blank=True, help_text='Permanent unique link for faculty to access their surveys', max_length=64, null=True, unique=True),
        ),
    ]
