# Generated by Django 6.0 on 2026-01-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0008_add_faculty_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(help_text='Lowercase code used internally (e.g., cardiac, critical_care)', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
