# Generated by Django 6.0 on 2026-01-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0009_remove_division_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date faculty is leaving/left. If blank, they receive survey invitations indefinitely.', null=True, verbose_name='End Date'),
        ),
    ]
