# Generated by Django 6.0 on 2026-01-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0010_add_faculty_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the verification')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_verifications', to='reports_app.academicyear')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='reports_app.division')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_verifications_made', to='reports_app.facultymember')),
            ],
            options={
                'ordering': ['-verified_at'],
                'unique_together': {('division', 'academic_year')},
            },
        ),
    ]
