# Generated by Django 6.0 on 2026-01-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0011_divisionverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('activity_index', models.IntegerField()),
                ('activity_hash', models.CharField(blank=True, help_text='SHA256 hash of activity content for change detection', max_length=64)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('stricken', 'Stricken'), ('flagged', 'Flagged')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for strike/flag or verification notes')),
                ('original_data', models.JSONField(blank=True, help_text='Original activity data before any edits', null=True)),
                ('suggested_edits', models.JSONField(blank=True, help_text='Suggested changes for flagged items', null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reviews', to='reports_app.academicyear')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reviews', to='reports_app.facultymember')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_made', to='reports_app.facultymember')),
            ],
            options={
                'ordering': ['category', 'subcategory', 'activity_index'],
                'unique_together': {('faculty', 'academic_year', 'category', 'subcategory', 'activity_index')},
            },
        ),
        migrations.CreateModel(
            name='FacultyAnnualReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('has_issues', 'Has Issues'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_annual_reviews', to='reports_app.academicyear')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_reviews', to='reports_app.facultymember')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_reviews_made', to='reports_app.facultymember')),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'unique_together': {('faculty', 'academic_year')},
            },
        ),
    ]
