# Generated by Django 6.0 on 2026-01-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0012_activityreview_facultyannualreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='review_mode_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, division chiefs can review and verify faculty activities'),
        ),
    ]
