# Generated by Django 6.0 on 2026-01-09 14:32

import django.db.models.deletion
import survey_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports_app', '0006_increase_year_code_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1-Q2', 'Q1-Q2 (Jul-Dec)'), ('Q3', 'Q3 (Jan-Mar)'), ('Q4', 'Q4 (Apr-Jun)')], max_length=10)),
                ('name', models.CharField(help_text='Display name, e.g., "AY 24-25 Q1-Q2 Survey"', max_length=100)),
                ('opens_at', models.DateTimeField(help_text='When survey becomes accessible')),
                ('closes_at', models.DateTimeField(help_text='Submission deadline')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive campaigns cannot accept submissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Username if authentication is enabled', max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_campaigns', to='reports_app.academicyear')),
            ],
            options={
                'verbose_name': 'Survey Campaign',
                'verbose_name_plural': 'Survey Campaigns',
                'ordering': ['-academic_year__year_code', '-quarter'],
                'unique_together': {('academic_year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=survey_app.models.generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='pending', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='survey_app.surveycampaign')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_invitations', to='reports_app.facultymember')),
            ],
            options={
                'verbose_name': 'Survey Invitation',
                'verbose_name_plural': 'Survey Invitations',
                'ordering': ['faculty__last_name', 'faculty__first_name'],
                'unique_together': {('campaign', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('invitation', 'Initial Invitation'), ('reminder', 'Reminder'), ('confirmation', 'Submission Confirmation')], max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='survey_app.surveyinvitation')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(default=dict, help_text='Survey response data structured by category')),
                ('citizenship_complete', models.BooleanField(default=False)),
                ('education_complete', models.BooleanField(default=False)),
                ('research_complete', models.BooleanField(default=False)),
                ('leadership_complete', models.BooleanField(default=False)),
                ('content_expert_complete', models.BooleanField(default=False)),
                ('citizenship_points', models.IntegerField(default=0)),
                ('education_points', models.IntegerField(default=0)),
                ('research_points', models.IntegerField(default=0)),
                ('leadership_points', models.IntegerField(default=0)),
                ('content_expert_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='survey_app.surveyinvitation')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
            },
        ),
    ]
