# Generated by Django 6.0 on 2026-01-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('submit', 'Submitted'), ('unlock', 'Unlocked')], max_length=20)),
                ('category', models.CharField(blank=True, help_text='Category that was modified (if applicable)', max_length=50)),
                ('response_data_snapshot', models.JSONField(default=dict, help_text='Complete response data at time of change')),
                ('points_snapshot', models.JSONField(default=dict, help_text='Points by category at time of change')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='survey_app.surveyresponse')),
            ],
            options={
                'verbose_name': 'Response History',
                'verbose_name_plural': 'Response History',
                'ordering': ['-created_at'],
            },
        ),
    ]
