# Generated by Django 6.0 on 2026-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0002_add_response_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycampaign',
            name='email_body',
            field=models.TextField(blank=True, default='', help_text='Email body. Use {first_name}, {last_name}, {survey_link}, {deadline} as placeholders.'),
        ),
        migrations.AddField(
            model_name='surveycampaign',
            name='email_from_address',
            field=models.EmailField(blank=True, default='', help_text='Sender email address', max_length=254),
        ),
        migrations.AddField(
            model_name='surveycampaign',
            name='email_from_name',
            field=models.CharField(blank=True, default='', help_text='Sender name (e.g., "Nick Markin")', max_length=100),
        ),
        migrations.AddField(
            model_name='surveycampaign',
            name='email_subject',
            field=models.CharField(blank=True, default='', help_text='Email subject (leave blank for default)', max_length=200),
        ),
    ]
