# Generated by Django 6.0 on 2026-01-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_add_email_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycampaign',
            name='reminder_body',
            field=models.TextField(blank=True, default='', help_text='Reminder email body. Use {first_name}, {last_name}, {survey_link}, {deadline}, {status} as placeholders.'),
        ),
        migrations.AddField(
            model_name='surveycampaign',
            name='reminder_subject',
            field=models.CharField(blank=True, default='', help_text='Reminder email subject (leave blank for default)', max_length=200),
        ),
        migrations.AlterField(
            model_name='surveycampaign',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1 (Jul-Sep)'), ('Q2', 'Q2 (Oct-Dec)'), ('Q3', 'Q3 (Jan-Mar)'), ('Q4', 'Q4 (Apr-Jun)'), ('Q1-Q2', 'Q1-Q2 Combined')], max_length=10),
        ),
    ]
