# Generated by Django 6.0 on 2026-01-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0004_add_reminder_email_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyConfigOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Custom Configuration', help_text='Name for this configuration', max_length=100)),
                ('config_json', models.JSONField(help_text='Complete survey configuration as JSON')),
                ('is_active', models.BooleanField(default=False, help_text='If true, this config overrides the default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Survey Config Override',
                'verbose_name_plural': 'Survey Config Overrides',
                'ordering': ['-updated_at'],
            },
        ),
    ]
