# Generated by Django 6.0 on 2026-01-28 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0013_academicyear_review_mode_enabled'),
        ('survey_app', '0005_add_survey_config_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyconfigoverride',
            options={'ordering': ['-academic_year__year_code', '-updated_at'], 'verbose_name': 'Survey Config', 'verbose_name_plural': 'Survey Configs'},
        ),
        migrations.AddField(
            model_name='surveyconfigoverride',
            name='academic_year',
            field=models.OneToOneField(blank=True, help_text='The academic year this config applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_config', to='reports_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='surveyconfigoverride',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, this config is ignored and default is used'),
        ),
        migrations.AlterField(
            model_name='surveyconfigoverride',
            name='name',
            field=models.CharField(default='Custom Configuration', help_text='Name for this configuration (e.g., "AY 25-26 Survey Config")', max_length=100),
        ),
    ]
