"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set SECRET_KEY environment variable
_secret_key = os.environ.get('SECRET_KEY', '')
if not _secret_key:
    # Allow insecure key ONLY in development when DEBUG is explicitly enabled
    _debug_env = os.environ.get('DEBUG', 'False').lower()
    if _debug_env in ('true', '1', 'yes'):
        _secret_key = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise RuntimeError(
            'SECRET_KEY environment variable is required. '
            'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
        )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# In production, set ALLOWED_HOSTS environment variable (comma-separated)
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports_app',
    'survey_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'reports_app.context_processors.academic_year_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'


# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
#
# DEFAULT (Development): SQLite for local development
# PRODUCTION: Configure via environment variables
#
# See DEPLOYMENT.md for full database configuration options.
# =============================================================================

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    },
}

# =============================================================================
# IT DEPLOYMENT: SHARED FACULTY DATABASE (Optional)
# =============================================================================
#
# If the department maintains a central faculty database, you can configure
# this application to read from it instead of maintaining a separate roster.
#
# To enable shared faculty database:
#
# 1. Uncomment the 'faculty_db' configuration below
# 2. Set the environment variables for the faculty database connection
# 3. Uncomment DATABASE_ROUTERS below
# 4. In reports_app/models.py, update FacultyMember.Meta:
#    - Set: managed = False
#    - Set: db_table = 'your_faculty_table_name'
#
# Environment variables needed:
#   FACULTY_DB_ENGINE   (e.g., django.db.backends.postgresql)
#   FACULTY_DB_NAME     (database name)
#   FACULTY_DB_USER     (database user)
#   FACULTY_DB_PASSWORD (database password)
#   FACULTY_DB_HOST     (database host)
#   FACULTY_DB_PORT     (database port, e.g., 5432 for PostgreSQL)
#
# =============================================================================

# DATABASES['faculty_db'] = {
#     'ENGINE': os.environ.get('FACULTY_DB_ENGINE', 'django.db.backends.postgresql'),
#     'NAME': os.environ.get('FACULTY_DB_NAME', ''),
#     'USER': os.environ.get('FACULTY_DB_USER', ''),
#     'PASSWORD': os.environ.get('FACULTY_DB_PASSWORD', ''),
#     'HOST': os.environ.get('FACULTY_DB_HOST', ''),
#     'PORT': os.environ.get('FACULTY_DB_PORT', '5432'),
# }

# =============================================================================
# Database Router for External Faculty Database
# Uncomment if using shared faculty database (see above)
# =============================================================================
# DATABASE_ROUTERS = ['reports_app.routers.FacultyRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'  # Central Time for UNMC

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
#
# Default: Console backend (prints emails to console for development)
# Production: Configure SMTP or transactional email service
#
# Environment variables:
#   EMAIL_BACKEND       - Django email backend class
#   EMAIL_HOST          - SMTP server hostname
#   EMAIL_PORT          - SMTP port (default: 587 for TLS)
#   EMAIL_USE_TLS       - Use TLS encryption (default: True)
#   EMAIL_HOST_USER     - SMTP username
#   EMAIL_HOST_PASSWORD - SMTP password or app-specific password
#   DEFAULT_FROM_EMAIL  - Default sender address
#
# =============================================================================

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'  # SMTP: sends real emails
)

# Directory for email files (only used with filebased backend)
EMAIL_FILE_PATH = os.environ.get('EMAIL_FILE_PATH', str(BASE_DIR / 'sent_emails'))

# SMTP Configuration (used when EMAIL_BACKEND is smtp)
# Default: UNMC internal mail relay (no auth required behind firewall)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'mail.unmc.edu')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'AVC Survey <noreply@unmc.edu>'
)

# Survey-specific email settings
SURVEY_EMAIL_SUBJECT_PREFIX = os.environ.get(
    'SURVEY_EMAIL_SUBJECT_PREFIX',
    '[UNMC Anesthesiology] '
)

# Site URL for email links (defaults to localhost for development)
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8001')


# =============================================================================
# PRODUCTION SECURITY SETTINGS
# =============================================================================
# These are automatically enabled when DEBUG=False

if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
